server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
#    ${ENVIROMENNT:DEFAULT}
    url: ${DBMS_CONNECTION:jdbc:mysql://172.17.0.2:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "xTEDJdqFuruTSqRKNpXqFb7nHAttDoQXCRQosRa7RjZhZH8GnhD8Ntq0SLz+SXUQ"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in second
