server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3310/identity_service"
    username: root
    password: Hieu@02042002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "xTEDJdqFuruTSqRKNpXqFb7nHAttDoQXCRQosRa7RjZhZH8GnhD8Ntq0SLz+SXUQ"